"""route reports and fuel refills

Revision ID: 6844573dc0ef
Revises: 
Create Date: 2026-07-23 20:04:14.725558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6844573dc0ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('route_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('route_from', sa.String(length=255), nullable=False),
    sa.Column('route_to', sa.String(length=255), nullable=False),
    sa.Column('odometer_start', sa.Integer(), nullable=False),
    sa.Column('odometer_end', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_end', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='report_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_reports_driver_id'), 'route_reports', ['driver_id'], unique=False)
    op.create_index(op.f('ix_route_reports_report_date'), 'route_reports', ['report_date'], unique=False)
    op.create_table('fuel_refills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('refill_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('liters', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_photo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['route_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_refills_report_id'), 'fuel_refills', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_refills_report_id'), table_name='fuel_refills')
    op.drop_table('fuel_refills')
    op.drop_index(op.f('ix_route_reports_report_date'), table_name='route_reports')
    op.drop_index(op.f('ix_route_reports_driver_id'), table_name='route_reports')
    op.drop_table('route_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
